name: Update Lint Rules

# TODO:
#   Set schedule event as soon as update mechanism is implemented.
#   https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#schedule
on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.1.0' # See: tools/update_lint_rules/pubspec.yaml

      - name: Install dependencies
        run: dart pub get
        shell: bash
        working-directory: tools/update_lint_rules

      - name: Run update_lint_rules
        run: dart run bin/update_lint_rules.dart "$GITHUB_WORKSPACE/lib"
        shell: bash
        working-directory: tools/update_lint_rules

      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID_OF_YUMEMI_PR_TOKEN_GENERATOR }}
          private_key: ${{ secrets.APP_PRIVATE_KEY_OF_YUMEMI_PR_TOKEN_GENERATOR }}

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.generate_token.outputs.token }}
          author: 'GitHub <noreply@github.com>'
          commit-message: 'auto: Update lint rules'
          title: Update lint rules
          body: This was automatically generated by the [${{ github.workflow }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
          base: main
          branch: auto/update-lint-rules
          branch-suffix: short-commit-hash
